services:
  frontend:
    build: ./my-app
    ports:
      - 5173:5173
    volumes:
      - ./my-app:/app
      - node_modules_1:/app/node_modules
    environment:
      - NODE_ENV=development

  server:
    build: ./server
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./server:/app
      - node_modules_2:/app/node_modules
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=secret
      - PG_DATABASE=mydb
      - PG_PORT=5432
      - MONGO_URI=mongodb://mongo/timemanager
      - MONGO_DB=timemanager
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:4.0.28-xenial
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  node_modules_1:
  node_modules_2:
  mongo_data:
